const actionTypes = {
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    RESET_REGISTER: 'RESET_REGISTER', // Add this line

    GET_COUNT_POSTS: 'GET_COUNT_POSTS',

    GET_POSTS: 'GET_POSTS',
    GET_POST_ID_SUCCESS: 'GET_POST_ID_SUCCESS',
    GET_POSTS_LIMIT: "GET_POSTS_LIMIT",
    GET_POSTS_ADMIN: 'GET_POSTS_ADMIN',
    GET_NEW_POST: "GET_NEW_POST",
    GET_POST_ID_FAIL: "GET_POST_ID_FAIL",
    EDIT_POST: 'EDIT_POST',
    RESET_DATAEDIT_POST: 'RESET_DATAEDIT_POST',

    GET_CATEGORIES: 'GET_CATEGORIES',
    GET_PRICES: 'GET_PRICES',
    GET_AREAS: 'GET_AREAS',
    GET_PROVINCES: 'GET_PROVINCES',

    CREATE_APPOINTMENT_SUCCESS: 'CREATE_APPOINTMENT_SUCCESS',
    FETCH_APPOINTMENTS_REQUEST: 'FETCH_APPOINTMENTS_REQUEST',
    FETCH_APPOINTMENTS_FAILURE: 'FETCH_APPOINTMENTS_FAILURE',
    FETCH_APPOINTMENTS_SUCCESS: 'FETCH_APPOINTMENTS_SUCCESS',
    GET_APPOINTMENTS_BYID_SUCCESS: '  GET_APPOINTMENTS_BYID_SUCCESS',
    GET_APPOINTMENTS_BYID_FAILURE: '  GET_APPOINTMENTS_BYID_FAILURE',
    GET_APPOINTMENTS_BYID_REQUEST: '  GET_APPOINTMENTS_BYID_REQUEST',

    FETCH_APPOINTMENTS_POSTER_REQUEST: 'FETCH_APPOINTMENTS_POSTER_REQUEST',
    FETCH_APPOINTMENTS_POSTER_FAILURE: 'FETCH_APPOINTMENTS_POSTER_FAILURE',
    FETCH_APPOINTMENTS_POSTER_SUCCESS: 'FETCH_APPOINTMENTS_POSTER_SUCCESS',

    APPROVE_APPOINTMENTS_SUCCESS: 'APPROVE_APPOINTMENTS_SUCCESS',
    APPROVE_APPOINTMENTS_FAILURE: 'APPROVE_APPOINTMENTS_FAILURE',

    CANCEL_APPOINTMENTS_SUCCESS: 'CANCEL_APPOINTMENTS_FAILURE',
    CANCEL_APPOINTMENTS_FAILURE: 'CANCEL _APPOINTMENTS_FAILURE',




    CREATE_COMMENT_REQUEST: 'CREATE_COMMENT_REQUEST',
    CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
    CREATE_COMMENT_FAILURE: 'CREATE_COMMENT_FAILURE',

    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_FAILURE: 'GET_COMMENTS_FAILURE',

    APPROVE_POST_SUCCESS: 'APPROVE_POST_SUCCESS',
    APPROVE_POST_FAILURE: 'APPROVE_POST_FAILURE',
    CANCEL_POST_SUCCESS: 'CANCEL_POST_SUCCESS',
    CANCEL_POST_FAILURE: 'CANCEL _POST_FAILURE',

    GET_RELATED_POSTS: 'GET_RELATED_POSTS',
    GET_RELATED_POSTS_FAILURE: 'GET_RELATED_POSTS_FAILURE',

    GET_POST_BY_START: 'GET_POST_BY_START',

    CALCULATE_AVERAGE_RENT_SUCCESS: 'CALCULATE_AVERAGE_RENT_SUCCESS',
    CALCULATE_AVERAGE_RENT_FAILURE: 'CALCULATE_AVERAGE_RENT_FAILURE',
    CALCULATE_AVERAGE_RENT_BY_PROVINCE_AND_DATE_SUCCESS: 'CALCULATE_AVERAGE_RENT_BY_PROVINCE_AND_DATE_SUCCESS',
    CALCULATE_AVERAGE_RENT_BY_PROVINCE_AND_DATE_FAILURE: 'CALCULATE_AVERAGE_RENT_BY_PROVINCE_AND_DATE_FAILURE',
    CALCULATE_AVERAGE_RENT_BY_ALL_PROVINCE_SUCCESS: 'CALCULATE_AVERAGE_RENT_BY_ALL_PROVINCE_SUCCESS',
    CALCULATE_AVERAGE_RENT_BY_ALL_PROVINCE_FAILURE: 'CALCULATE_AVERAGE_RENT_BY_ALL_PROVINCE_FAILURE',

    GET_MARKED_POSTS: 'GET_MARKED_POSTS',
    GET_MARKED_POSTS_SUCCESS: 'GET_MARKED_POSTS_SUCCESS',
    GET_MARKED_POSTS_FAILURE: 'GET_MARKED_POSTS_FAILURE',



    // USER
    GET_CURRENT: 'GET_CURRENT',
    GET_ALL_USER: ' GET_ALL_USER',

    FETCH_USER_CONVERSATIONS_REQUEST: 'FETCH_USER_CONVERSATIONS_REQUEST',
    FETCH_USER_CONVERSATIONS_SUCCESS: 'FETCH_USER_CONVERSATIONS_SUCCESS',
    FETCH_USER_CONVERSATIONS_FAILURE: ' FETCH_USER_CONVERSATIONS_FAILURE',

    FETCH_USER_CONVERSATIONS_BY_USER_REQUEST: 'FETCH_USER_CONVERSATIONS_BY_USER_REQUEST',
    FETCH_USER_CONVERSATIONS_BY_USER_SUCCESS: 'FETCH_USER_CONVERSATIONS_BY_USER_SUCCESS',
    FETCH_USER_CONVERSATIONS_BY_USER_FAILURE: ' FETCH_USER_CONVERSATIONS_BY_USER_FAILURE',

    FETCH_MESSAGES_BY_ROOM_SUCCESS: 'FETCH_MESSAGES_BY_ROOM_SUCCESS',
    FETCH_MESSAGES_BY_ROOM_FAILURE: 'FETCH_MESSAGES_BY_ROOM_FAILURE',
    FETCH_MESSAGES_BY_ROOM_REQUEST: 'FETCH_MESSAGES_BY_ROOM_REQUEST',

    FETCH_MESSAGES_LASTED_BY_ROOM_SUCCESS: 'FETCH_MESSAGES_LASTED_BY_ROOM_SUCCESS',
    FETCH_MESSAGES_LASTED_BY_ROOM_FAILURE: 'FETCH_MESSAGES_LASTED_BY_ROOM_FAILURE',
    FETCH_MESSAGES_LASTED_BY_ROOM_REQUEST: 'FETCH_MESSAGES_LASTED_BY_ROOM_REQUEST',

    FETCH_TOTAL_UNREAD_MESSAGES_REQUEST: 'FETCH_TOTAL_UNREAD_MESSAGES_REQUEST',
    FETCH_TOTAL_UNREAD_MESSAGES_SUCCESS: 'FETCH_TOTAL_UNREAD_MESSAGES_SUCCESS',
    FETCH_TOTAL_UNREAD_MESSAGES_FAILURE: 'FETCH_TOTAL_UNREAD_MESSAGES_FAILURE',

    FETCH_TOTAL_UNREAD_NOTIFICATION_REQUEST: 'FETCH_TOTAL_UNREAD_NOTIFICATION_REQUEST',
    FETCH_TOTAL_UNREAD_NOTIFICATION_SUCCESS: 'FETCH_TOTAL_UNREAD_NOTIFICATION_SUCCESS',
    FETCH_TOTAL_UNREAD_NOTIFICATION_FAILURE: 'FETCH_TOTAL_UNREAD_NOTIFICATION_FAILURE',




};

export default actionTypes;